#!/usr/bin/env bash

# set color contants
GREEN='\033[1;32m'
RED='\033[1;31m'
YELLO='\033[1;33m'
END='\033[0m'

if [ $# -eq 0 ];then
        echo -e "${RED}[ Error ] Require one port!\n${END}"
else
        for i in $@
        do
                iptables -A INPUT -p TCP --dport $i -j DROP
                if [ $? -eq 0 ];then
                        echo -e "${GREEN}[ Success ] Port ${i} is already closed!\n${END}"
                fi
        done
        echo -e "${YELLO}[ iptables INPUT list ]${END}"
        iptables -L INPUT --line-numbers
fi
