#!/usr/bin/env bash

GREEN='\033[3;32m'
RED='\033[1;31m'
YELLO='\033[1;33m'
END='\033[0m'

if [ $# -eq 0 ];then
	echo -e "${RED}Require a list number!${END}"
else
	for i in $@
	do
		iptables -D INPUT $i
		echo -e "${GREEN}list number $i is already delete${END}"
	done
	iptables -L INPUT --line-numbers
fi
