#!/usr/bin/env bash

### Tools function and terminal run

### set color variable
GREEN='\033[3;32m'
RED='\033[1;31m'
YELLO='\033[1;33m'
END='\033[0m'
SUBDOMAIN=/root/subdomain/
RESULT=/root/result/

### ErrorArray funtion
function ea()
{
	if [ $? -ne 0 ];then
		array[${#array[*]}]="$1"
	fi
}

### subdomain gathering function

# function fesd(){
# 	echo -e "${GREEN}start esd${END}"
# 	terminal -e "esd -d $1" -T "ESD" 2>&1 &
# 	ea 'esd'
# }

# function foneforall(){
# 	echo -e "${GREEN}start oneforall${END}"
# 	terminal -e "oneforall --port large --brute --path ${RESULT}/oneforall.csv --target $1 run" -T "Oneforall" 2>&1 &
# 	ea 'oneforall'
# }

# function fsublist3r(){
# 	echo -e "${GREEN}start sublist3r${END}"
# 	terminal -e "sublist3r-b -v -o ${RESULT}sublist3r -d $1" -T "Sublist3r" 2>&1 &
# 	ea 'sublist3r'

# }



# function ffierce(){
# 	echo -e "${GREEN}start fierce${END}"
# 	fierce --wide --domain $1 >> ${RESULT}fierce 2>&1
# 	ea 'fierce'
# 	sleep 2
# }

### Shell
function fctfr(){
	echo -e "${GREEN}start ctfr${END}"
	ctfr -d $1 -o ${RESULT}ctfr
	ea 'ctfr'
	sleep 2
}

function fassetfinder(){
	echo -e "${GREEN}start assetfinder${END}"
	assetfinder $1 >> ${RESULT}assetfinder 2>&1
	ea 'assetfinder'
	sleep 2
}


function fsubfinder(){
	echo -e "${GREEN}start subfinder${END}"
	subfinder -d $1 --all -o ${RESULT}subfinder_nodns
	sleep 2

	subfinder -d $1 --all -o ${RESULT}subfinder_dns -r 8.8.8.8,223.6.6.6,180.76.76.76,1.1.1.1
	ea 'subfinder'
	sleep 2
}

function fknock(){
	echo -e "${GREEN}start knock${END}"
	knock --useragent "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)" --recon --bruteforce -d $1 --save ${RESULT}
	ea 'knock'
	sleep 2
}

function ffindomain(){
	echo -e "${GREEN}start findomain${END}"
	findomain --ua ${SUBDOMAIN}findomain/ua  --pscan -t $1 -u ${RESULT}findomain
	ea 'findomain'
	sleep 2
}

function fdnsmap(){
	echo -e "${GREEN}start dnsmap${END}"
	dnsmap $1 -r ${RESULT}dnsmap
	ea 'dnsmap'
	sleep 2
}

function fgithub-subdomains(){
	echo -e "${GREEN}start fgithub-subdomains ${END}"
	github-subdomains -t /root/subdomain/github-subdomains/.tokens -d $1 -o ${RESULT}github-subdomains
	ea 'github-subdomains'
	sleep 2
}

### Spending time

function fsubdomainsbrute(){
	echo -e "${GREEN}start subdomainsbrute${END}"
	subdomainbrute --full $1 -o ${RESULT}subdomainbrute
	ea 'subdomainsbrute'

}

function fksubdomain(){
	echo -e "${GREEN}start ksubdomain${END}"
	ksubdomain -d $1 --full --csv -o ${RESULT}ksubdomain.csv
	ea 'ksubdomain'

}

function fdnsub(){
	echo -e "${GREEN}start dnsub${END}"
	cd ${SUBDOMAIN}dnsub 
	./dnsub -d $1 --depth 3 -o /root/dnsub.csv
	ea 'dnsub'

	cd /root
}

function CycleArray()
{
	for i in ${array[*]}
	do
		echo $i
	done
}


echo -e "${RED}START${END}"

echo -e "${YELLO}input target domain${END}"
### GET domain
read domain

### function 

#foneforall $domain
#fesd $domain   # 一小时
#fsublist3r $domain
# ffierce $domain

fctfr $domain
fsubfinder $domain
ffindomain $domain
fknock $domain
fassetfinder $domain
fdnsmap $domain
fsubdomainsbrute $domain
fdnsub $domain
fksubdomain $domain
fgithub-subdomains $domain


echo -e "${RED}Error${END}"
CycleArray

echo -e "${RED}Manual test${END}"
echo -e "${GREEN}esd${END}"
echo -e "${GREEN}OneForAll${END}"
echo -e "${GREEN}sublist3r${END}"
echo -e "${GREEN}fierce${END}"
echo -e "${GREEN}aquatone${END}"
echo -e "${GREEN}chaos${END}"


echo -e "${RED}All Tools are done!${END}"