#!/usr/bin/env bash

RED='\033[1;31m'
END='\033[0m'

if [ $# -eq 0 ];then
	echo -e "${RED}Please enter the parameters!${END}"
	exit
fi

for i in $@
do
	echo -e "${RED}${i}${END} "
	echo "$(ps -ef |grep ${i} |grep -v grep|grep -v getps)"
done
