#!/usr/bin/env bash

GREEN='\033[3;32m'
RED='\033[1;31m'
YELLO='\033[1;33m'
END='\033[0m'

if [ $# -ne 0 ];then
        for i in $@
        do
                kill -9 $i
                echo -e "${GREEN}$i has been killd!${END}"
        done
else
        echo -e "${RED}Give me a PID!${END}"
fi